.TH "player" 3 "Tue May 26 2015" "Version 1.0" "Player" \" -*- nroff -*-
.ad l
.nh
.SH NAME
player \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCPlayer\fP"
.br
.RI "\fIclasse representant le lecteur \fP"
.in -1c
.SH "Detailed Description"
.PP 
espace de nommage regroupant les outils composants un lecteur audio 
.SH "Author"
.PP 
Generated automatically by Doxygen for Player from the source code\&.
