.TH "player.h" 3 "Tue May 26 2015" "Version 1.0" "Player" \" -*- nroff -*-
.ad l
.nh
.SH NAME
player.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <list>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBplayer::CPlayer\fP"
.br
.RI "\fIclasse representant le lecteur \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBplayer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Player from the source code\&.
